---

- name: add key
  apt_key:
    url: "{{ php_custom_repositories_key_url }}"
    state: present
  when: php_use_custom_repository

- name: add repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ php_custom_repositories }}"
  when: php_use_custom_repository

- name: install apt packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ php_packages }}"

- name: list default pools
  shell: "ls -1 {{ php_fpm_root_dir }}/fpm/pool.d"
  register: default_pools
  changed_when: False

- name: delete default pools
  file:
    path: "{{ php_fpm_root_dir }}/fpm/pool.d/{{ item }}"
    state: absent
  with_items: "{{ default_pools.stdout_lines }}"
  when: item != "pools.conf"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ php_fpm_root_dir }}/fpm/{{ item }}"
  with_items:
    - php.ini
    - php-fpm.conf
    - opcache.blacklist
    - pool.d/pools.conf
  notify:
    - restart php-fpm

- name: config CLI
  template:
    src: "{{ item }}.j2"
    dest: "{{ php_fpm_root_dir }}/cli/{{ item }}"
  with_items:
    - php.ini

- name: modules config
  template:
    src: "{{ item }}.j2"
    dest: "{{ php_fpm_root_dir }}/mods-available/{{ item }}"
  with_items:
    - custom.ini
  notify:
    - restart php-fpm

- include: composer.yml
  when: php_composer_enabled

- include: blackfire.yml
  when: php_blackfire_enabled

- include: newrelic.yml
  when: php_newrelic_enabled

- name: enable modules
  shell: "/usr/sbin/phpenmod {{ item }}"
  with_items:
    - newrelic
    - custom
  notify:
    - restart php-fpm
  changed_when: False

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - php7.0-fpm
